import { writeFile, readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import type { ScanResult } from "../types.js";

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

function generateContext(result: ScanResult): string {
  const { project, routes, schemas, components, middleware, config, graph } = result;

  const lines: string[] = [];

  // Stack overview
  const fw = project.frameworks.join(", ") || "generic";
  const orm = project.orms.join(", ") || "none";
  lines.push(`This is a ${project.language} project using ${fw}${orm !== "none" ? ` with ${orm}` : ""}.`);

  if (project.isMonorepo) {
    lines.push(`It is a monorepo with workspaces: ${project.workspaces.map((w) => `${w.name} (${w.path})`).join(", ")}.`);
  }

  lines.push("");

  // Key architecture facts
  if (routes.length > 0) {
    lines.push(`The API has ${routes.length} routes. See .codesight/routes.md for the full route map with methods, paths, and tags.`);
  }
  if (schemas.length > 0) {
    lines.push(`The database has ${schemas.length} models. See .codesight/schema.md for the full schema with fields, types, and relations.`);
  }
  if (components.length > 0) {
    lines.push(`The UI has ${components.length} components. See .codesight/components.md for the full list with props.`);
  }
  if (middleware.length > 0) {
    const types = [...new Set(middleware.map((m) => m.type))].join(", ");
    lines.push(`Middleware includes: ${types}.`);
  }

  lines.push("");

  // Hot files (most imported = most impactful to change)
  if (graph.hotFiles.length > 0) {
    lines.push("High-impact files (most imported, changes here affect many other files):");
    for (const hf of graph.hotFiles.slice(0, 8)) {
      lines.push(`- ${hf.file} (imported by ${hf.importedBy} files)`);
    }
    lines.push("");
  }

  // Required env vars
  const requiredEnvs = config.envVars.filter((e) => !e.hasDefault);
  if (requiredEnvs.length > 0) {
    lines.push("Required environment variables (no defaults):");
    for (const env of requiredEnvs.slice(0, 15)) {
      lines.push(`- ${env.name} (${env.source})`);
    }
    lines.push("");
  }

  lines.push("Read .codesight/CODESIGHT.md for the complete AI context map including all routes, schema, components, libraries, config, middleware, and dependency graph.");

  return lines.join("\n");
}

export async function generateAIConfigs(
  result: ScanResult,
  root: string
): Promise<string[]> {
  const generated: string[] = [];
  const context = generateContext(result);

  // --- CLAUDE.md ---
  const claudePath = join(root, "CLAUDE.md");
  const claudeExists = await fileExists(claudePath);
  if (!claudeExists) {
    const claudeContent = `# Project Context

${context}
`;
    await writeFile(claudePath, claudeContent);
    generated.push("CLAUDE.md");
  } else {
    // Check if it already references codesight
    const existing = await readFile(claudePath, "utf-8");
    if (!existing.includes("codesight") && !existing.includes("CODESIGHT")) {
      // Append context section
      const appendSection = `

# AI Context (auto-generated by codesight)

${context}
`;
      await writeFile(claudePath, existing + appendSection);
      generated.push("CLAUDE.md (appended)");
    }
  }

  // --- .cursorrules ---
  const cursorPath = join(root, ".cursorrules");
  const cursorExists = await fileExists(cursorPath);
  if (!cursorExists) {
    const cursorContent = `# Project Context

${context}
`;
    await writeFile(cursorPath, cursorContent);
    generated.push(".cursorrules");
  }

  // --- .github/copilot-instructions.md ---
  const copilotDir = join(root, ".github");
  const copilotPath = join(copilotDir, "copilot-instructions.md");
  const copilotExists = await fileExists(copilotPath);
  if (!copilotExists) {
    // Only create if .github dir exists (don't create it for non-GitHub projects)
    const ghDirExists = await fileExists(copilotDir);
    if (ghDirExists) {
      const copilotContent = `# Project Context

${context}
`;
      await writeFile(copilotPath, copilotContent);
      generated.push(".github/copilot-instructions.md");
    }
  }

  // --- codex.md (OpenAI Codex CLI) ---
  const codexPath = join(root, "codex.md");
  const codexExists = await fileExists(codexPath);
  if (!codexExists) {
    const codexContent = `# Project Context

${context}
`;
    await writeFile(codexPath, codexContent);
    generated.push("codex.md");
  }

  // --- AGENTS.md (OpenAI Codex) ---
  const agentsPath = join(root, "AGENTS.md");
  const agentsExists = await fileExists(agentsPath);
  if (!agentsExists) {
    const agentsContent = `# Project Context

${context}
`;
    await writeFile(agentsPath, agentsContent);
    generated.push("AGENTS.md");
  }

  return generated;
}
